### PR TITLE
Support PostProcess on Unity 4.6

### PR DESCRIPTION
**Pull request by lacostej**
Not really sure why 4.6 isn't supported as a post build.

Here's a potential patch that fixes it.

Note that I wonder if we could make the AdSupport optional.

### CODE REVIEW

**Comment by the1schwartz** [comment]
Hi,

Thank you for using GameAnalytics and thank you for the pull request. The XCode API is first included directly in Unity 5, but it looks like Unity has made it open source. It can be downloaded here https://bitbucket.org/Unity-Technologies/xcodeapi/downloads. You just need to compile the code and copy the .dll into the Plugins folder and then it should work. We will update our documentation to mention all of this.

Kind regards,
Martin
SDK Developer

**Comment by lacostej** [comment]
The DLL is packaged with Unity 4.6.

    > ls -la /Applications/Unity*///Unity.app/Contents/PlaybackEngines/iossupport/UnityEditor.iOS.Extensions.Xcode.dll
    -rwxrwxr-x  1 root  admin  61440 Jan 26 21:17 /Applications/Unity4.6.2f1/Unity.app/Contents/PlaybackEngines/iossupport/UnityEditor.iOS.Extensions.Xcode.dll
    -rwxrwxr-x  1 root  admin  65024 Feb 18 17:14 /Applications/Unity4.6.3f1/Unity.app/Contents/PlaybackEngines/iossupport/UnityEditor.iOS.Extensions.Xcode.dll
    -rwxrwxr-x  1 root  admin  68608 Mar  4 21:10 /Applications/Unity4.6.3p2/Unity.app/Contents/PlaybackEngines/iossupport/UnityEditor.iOS.Extensions.Xcode.dll
    -rwxrwxr-x  1 root  admin  68608 Apr 27 12:31 /Applications/Unity4.6.5f1/Unity.app/Contents/PlaybackEngines/iossupport/UnityEditor.iOS.Extensions.Xcode.dll

**Comment by the1schwartz** [comment]
Ah yeah I can see that. Thank you for poiting that out, but it still seems that you need to copy the UnityEditor.iOS.Extensions.Xcode.dll into the plugins folder before it can compile or else I get that iOS doesn't exist in the UnityEditor namespace. Or this there something I am missing to do?

**Comment by lacostej** [comment]
It looks like one still needs to add the library under Plugins/.
I posted http://forum.unity3d.com/threads/xcodeapi-support-under-4-6.336363/

**Pull request closed without merging**
